### ISSUE TITLE
Install of v0.3.5 from PyPI creates broken build due to TFP v0.8

### ISSUE THREAD

**Issue by matthewfeickert** [zfit/zfit#174]
## Current Behaviour

In a clean Python 3.6.8 virtual environment `pip install zfit` will succeed but then creates an unsuable version.

```
(zfit) $ pip list
Package    Version
---------- -------
pip        19.2.3 
setuptools 41.4.0 
wheel      0.33.6 
(zfit) $ pip install zfit
(zfit) $ pip freeze | grep tensor
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-probability==0.8.0
$ python
>>> import tensorflow as tf
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
>>> import zfit
WARNING:tensorflow:From /home/mcf/venvs/zfit/lib/python3.6/site-packages/zfit/util/execution.py:137: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mcf/venvs/zfit/lib/python3.6/site-packages/zfit/__init__.py", line 24, in <module>
    from . import ztf  # legacy
  File "/home/mcf/venvs/zfit/lib/python3.6/site-packages/zfit/ztf/__init__.py", line 44, in <module>
    from . import random
  File "/home/mcf/venvs/zfit/lib/python3.6/site-packages/zfit/ztf/random.py", line 5, in <module>
    import tensorflow_probability as tfp
  File "/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 68, in <module>
    _ensure_tf_install()
  File "/home/mcf/venvs/zfit/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 65, in _ensure_tf_install
    present=tf.__version__))
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 1.15; Detected an installation of version 1.14.0. Please upgrade TensorFlow to proceed.
```

This is the result of [TensorFlow Probability `v0.8`](https://github.com/tensorflow/probability/releases/tag/0.8.0) only supporting TensorFlow `v1.15` (which is not out yet) and TensorFlow `v2.0`.

## Expected Behaviour

The import succeeds

## Context (Environment)

* zfit version: `v0.3.5`
* Python version: `3.6.8` built from source
* Are you using conda, pipenv, etc? : Python 3 `venv` + `pip`
* Operating System: Ubuntu 16.04
* Tensorflow version:
```
$ pip freeze | grep tensorflow
tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-probability==0.8.0
```

## Possible Solution/Implementation

Wait until TF `v1.15.0` is out or in `setup.py` use something like
```python
'tensorflow-probability~=0.5,<0.8',
```

**Comment by matthewfeickert** [comment]
> It's tricky though, since zfit also runs with TF 2.0 where tfp 0.8 could be helpful (and older versions had some failures if I remember correctly).

Yes. I'm just reporting this as it breaks the PyPI installs at the moment. But as I said

> Wait until TF v1.15.0 is out

is probably the best solution. They're on `v1.15.0-rc3` at the moment, so my guess is by next week this is resolved for you.

> zfit also runs with TF 2.0

It is already TF 2.0 compliant? Impressive.

**Comment by mayou36** [comment]
> is probably the best solution. They're on `v1.15.0-rc3` at the moment, so my guess is by next week this is resolved for you.

yes, I think so too

> It is already TF 2.0 compliant? Impressive.

Not eager mode though (that's a different beast), but all the syntax and other changes, yes.

**Comment by mayou36** [comment]
We've released a new version since there is also other odd behavior with tf 2.0. Pip install should now work out again.
