### ISSUE TITLE
Problem with `_cache_add_constraints`

### ISSUE THREAD

**Issue by marinang** [zfit/zfit#178]
It seems there is a problem with cached Loss and addition of constraints in the case where I want the see the value of the loss function with `zfit.run(nll.value())` before adding the constraint.

## Current Behaviour

```python

>>> nll  = ExtendedUnbinnedNLL(model=model, data=data)
>>> print(zfit.run(nll.value())) 
>>> nll.add_constraints(GaussianConstraint(...))

Traceback (most recent call last):
  File "zfit_bpvcorrm_dr.py", line 400, in <module>
    nll.add_constraints(constraint_hdr(mu_hdr, sigma_hdr, nu_hdr, tau_hdr, year=ysim))
  File "/Users/matthieumarinangeli/anaconda3/envs/tfn/lib/python3.7/site-packages/zfit/core/loss.py", line 165, in add_constraints
    return self._add_constraints(constraints)
  File "/Users/matthieumarinangeli/anaconda3/envs/tfn/lib/python3.7/site-packages/zfit/core/loss.py", line 247, in _add_constraints
    self._cache_add_constraints(constraints=constraints)
  File "/Users/matthieumarinangeli/anaconda3/envs/tfn/lib/python3.7/site-packages/zfit/core/loss.py", line 279, in _cache_add_constraints
    constraints = [c.value() for c in constraints]
TypeError: 'GaussianConstraint' object is not iterable

```
## Expected Behaviour

This should not raise an error, if I remove `print(zfit.run(nll.value()))` it works.

## Context (Environment)

* zfit version: 0.3.6
* Python version: 3.7
* Are you using conda, pipenv, etc? : conda
* Operating System: MacOS / Linux
* Tensorflow version: 1.14

**Comment by mayou36** [comment]
Fixed, missed preprocessing in `add_constraints`.
