### ISSUE TITLE
Issue in 2D model unbinned data construction

### ISSUE THREAD

**Issue by zazbone** [zfit/zfit#482]
**Bugs**

I'm trying to move an analysis model build with RooFit to zfit, 
and I ran into a problem during data importation.
I've managed to reproduce a minimal example:

```python
import numpy as np
import pandas as pd
import zfit as zf
import zfit.z as zb
import zfit.z.numpy

class Simple2DModel(zf.pdf.ZPDF):
    _N_OBS = 2
    _PARAMS = ("a", "b", "c", "sigma")

    def _unnormalized_pdf(self, x):
        x, y = x.unstack_x()
        mean = self.params["c"] + self.params["b"] * x + self.params["a"] * zb.square(x)
        model = zf.pdf.Gauss(mean, self.params["sigma"], y)
        return model

a = zf.Parameter("a", 0, -1, 1)
b = zf.Parameter("b", 0.1, 0, 1)
c = zf.Parameter("c", 3, 0, 10)
sigma = zf.Parameter("sigma", 0.1, 0.0001, 0.5)

x = zf.Space("x", (0, 10))
y = zf.Space("y", (0, 100))
space = x * y

model = Simple2DModel(space, "model", a=a, b=b, c=c, sigma=sigma)

rng = np.random.default_rng()
xdata = rng.uniform(0, 10, 1<<15)
mu = 0.001 * xdata ** 2 + 0.12 * xdata + 4
ydata = rng.normal(mu, 0.2341, 1<<15)
df = pd.DataFrame({
    "x": xdata, "y": ydata
})
fit_data = zf.Data.from_pandas(df, space)

nll = zf.loss.UnbinnedNLL(model=model, data=fit_data)
```

## Current Behaviour

The example can be run in the terminal and throw the following error:

```
$ python scripts/error.py 
/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/__init__.py:63: UserWarning: TensorFlow warnings are by default suppressed by zfit. In order to show them, set the environment variable ZFIT_DISABLE_TF_WARNINGS=0. In order to suppress the TensorFlow warnings AND this warning, set ZFIT_DISABLE_TF_WARNINGS=1.
  warnings.warn(
Traceback (most recent call last):
  File "/home/zazbone/Documents/Codes/rooster2/scripts/error.py", line 38, in <module>
    nll = zf.loss.UnbinnedNLL(model=model, data=fit_data)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/loss.py", line 705, in __init__
    super().__init__(
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/loss.py", line 208, in __init__
    self._precompile()
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/loss.py", line 336, in _precompile
    self._call_value(
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/loss.py", line 466, in _call_value
    value = self._value(
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/loss.py", line 482, in _value
    return self._loss_func(
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/loss.py", line 724, in _loss_func
    return self._loss_func_watched(
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/z/zextension.py", line 293, in concrete_func
    result = func_to_run(*args, **kwargs)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/loss.py", line 738, in _loss_func_watched
    nll = _unbinned_nll_tf(
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/loss.py", line 84, in _unbinned_nll_tf
    nlls = [
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/loss.py", line 85, in <listcomp>
    _unbinned_nll_tf(model=p, data=d, fit_range=r, log_offset=log_offset)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/loss.py", line 96, in _unbinned_nll_tf
    probs = model.pdf(data)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/util/deprecation.py", line 16, in wrapper
    return func(*args, norm=norm, **kwargs)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/z/zextension.py", line 242, in concrete_func
    return func(*args, **kwargs)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/basepdf.py", line 408, in pdf
    value = self._single_hook_pdf(x=x, norm=norm)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/basepdf.py", line 416, in _single_hook_pdf
    return self._hook_pdf(x=x, norm=norm)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/basepdf.py", line 419, in _hook_pdf
    return self._norm_pdf(x=x, norm=norm)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/basepdf.py", line 422, in _norm_pdf
    return self._call_pdf(x=x, norm=norm)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/basepdf.py", line 435, in _call_pdf
    return self._fallback_pdf(x, norm)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/basepdf.py", line 438, in _fallback_pdf
    pdf = self._call_unnormalized_pdf(x)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/basepdf.py", line 271, in _call_unnormalized_pdf
    return self._unnormalized_pdf(x)
  File "/home/zazbone/Documents/Codes/rooster2/scripts/error.py", line 15, in _unnormalized_pdf
    model = zf.pdf.Gauss(mean, self.params["sigma"], y)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/models/dist_tfp.py", line 239, in __init__
    super().__init__(
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/models/dist_tfp.py", line 96, in __init__
    super().__init__(obs=obs, dtype=dtype, name=name, params=params, **kwargs)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/basepdf.py", line 134, in __init__
    super().__init__(obs=obs, dtype=dtype, name=name, params=params, **kwargs)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/basemodel.py", line 130, in __init__
    self._check_set_space(obs)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/basemodel.py", line 219, in _check_set_space
    obs = Space(obs=obs)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/space.py", line 1214, in __init__
    super().__init__(obs=obs, axes=axes, name=name)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/space.py", line 805, in __init__
    coords = Coordinates(obs, axes)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/coordinates.py", line 24, in __init__
    obs, axes, n_obs = self._check_convert_obs_axes(obs, axes)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/coordinates.py", line 40, in _check_convert_obs_axes
    obs = convert_to_obs_str(obs, container=tuple)
  File "/home/zazbone/Documents/Codes/rooster2/venv/lib/python3.10/site-packages/zfit/core/coordinates.py", line 480, in convert_to_obs_str
    raise TypeError(f"Observables have to be string, not {ob} as in {obs}")
TypeError: Observables have to be string, not Tensor("unstack_x:1", shape=(None,), dtype=float64) as in (<tf.Tensor 'unstack_x:1' shape=(None,) dtype=float64>,)
```
I don't know enough about how the lib works to understand the full traceback :sweat: 

## Context (Environment)

- zfit version: 0.14.1
- Python version: CPython 3.10.6
- Are you using conda, pipenv, etc? : pip install zfit[all]
- Operating System: Linux mint
- Tensorflow version: 2.12.1

**Comment by jonas-eschle** [comment]
Hi @zazbone thanks for reporting this! This should be used slightly different, I would say the best way is probably to use `tfp.distributions.Normal(loc, scale)`, i.e. to do

```
import tensorflow_probability as tfp

class Simple2DModel(zf.pdf.ZPDF):
    _N_OBS = 2
    _PARAMS = ("a", "b", "c", "sigma")

    def _unnormalized_pdf(self, x):
        x, y = x.unstack_x()
        mean = self.params["c"] + self.params["b"] * x + self.params["a"] * zb.square(x)
        model = tfp.distributions.Normal(mean, self.params["sigma"]).prob(y)
        return model
```
(assuming that mean is meant to be the mean of the gaussian and y what is usually the data)

Does that do the trick?

**Comment by zazbone** [comment]
Hi Jonas,

Ok, it works, so it is not mandatory to use only backend independent functions from zfit.z ?
And other zfit PDF or custom PDF are not usable to compose others ?

In my use case, the model that I use is a PDF sum (with a fraction) of a crystal ball and a Gaussian dist. 
Should I rewrite SumPDF and the crystal ball with tensorflow functions ?

Thanks
