### ISSUE TITLE
Binned fits with truncated PDFs not working

### ISSUE THREAD

**Issue by fchinu** [zfit/zfit#579]
## Current Behaviour
When trying to fit a binned truncated PDF, the execution throws an error for `IllegalInGraphModeError`.

Here is a minimal code example:

```
import zfit 
import numpy as np

low, high = -5, 10
binning = zfit.binned.RegularBinning(15, low, high, name="obs") # Define the binning for the observable
obs = zfit.Space(obs='obs', binning=binning)                    # Create the observable space
obs_unbinned = zfit.Space('obs', low, high)                     # Create the observable space

size_normal = 10_000                                            # Set the size of the normal distribution data
data_normal_np = np.random.normal(size=size_normal, scale=2)    # Generate normal distribution data

data_normal = zfit.Data(data_normal_np, obs=obs)                # Create a zfit Data object with the normal distribution data

mu = zfit.Parameter('mu', 1, -3, 3, step_size=0.2)              # Create a parameter for the mean of the first Gaussian
sigma = zfit.Parameter('sigma', 1, 0.1, 100)                    # Create a parameter for the standard deviation of the first Gaussian

gauss = zfit.pdf.Gauss(obs=obs_unbinned, mu=mu, sigma=sigma)    # Create a Gaussian PDF

pdf = gauss.to_truncated(limits=[[-5, -3], [3, 10]], obs=obs)   # Truncate the Gaussian PDF

sample = gauss.sample(n=1000)                                   # Generate a sample from the first Gaussian PDF

nll_gauss = zfit.loss.BinnedNLL(pdf, data_normal)               # Create the binned negative log-likelihood loss function
minimizer = zfit.minimize.Minuit()                              # Create a Minuit minimizer
result = minimizer.minimize(nll_gauss)                          # Minimize the negative log-likelihood function
```
And also another one where two `PDF`s are summed, and then the `SumPDF` object is truncated:

```
import zfit 
import numpy as np

binning = zfit.binned.RegularBinning(15, -5, 10, name="obs")    # Define the binning for the observable
obs = zfit.Space(obs='obs', binning=binning)                    # Create the observable space

size_normal = 10_000                                            # Set the size of the normal distribution data
data_normal_np = np.random.normal(size=size_normal, scale=2)    # Generate normal distribution data

data_normal = zfit.Data(data_normal_np, obs=obs)                # Create a zfit Data object with the normal distribution data

mu = zfit.Parameter('mu', 1, -3, 3, step_size=0.2)              # Create a parameter for the mean of the first Gaussian
mu2 = zfit.Parameter('mu2', 2, -3, 3, step_size=0.2)            # Create a parameter for the mean of the second Gaussian
sigma = zfit.Parameter('sigma', 1, 0.1, 100)                    # Create a parameter for the standard deviation of the first Gaussian
sigma2 = zfit.Parameter('sigma2', 3, 0.1, 100)                  # Create a parameter for the standard deviation of the second Gaussian

gauss = zfit.pdf.Gauss(obs=obs, mu=mu, sigma=sigma)             # Create the first Gaussian PDF
gauss2 = zfit.pdf.Gauss(obs=obs, mu=mu2, sigma=sigma2)          # Create the second Gaussian PDF

pdf = zfit.pdf.SumPDF([gauss, gauss2], [0.5]).to_truncated(
                      limits=[[-5, -3], [3, 10]])               # Create the sum PDF with the two Gaussians

sample = gauss.sample(n=1000)                                   # Generate a sample from the first Gaussian PDF

nll = zfit.loss.BinnedNLL(pdf, data_normal)                     # Create the binned negative log-likelihood loss function
minimizer = zfit.minimize.Minuit()                              # Create a Minuit minimizer
result = minimizer.minimize(nll)                                # Minimize the negative log-likelihood function
```

Both the two codes throw this error (here reported only for the second example):

```
Traceback (most recent call last):
  File "/home/fchinu/Run3/B0_Analysis/Tests/zfit_issue.py", line 27, in <module>
    result = minimizer.minimize(nll)                                # Minimize the negative log-likelihood function
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/minimizers/baseminimizer.py", line 486, in minimize
    return self._call_minimize(loss=loss, params=params, init=init)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/minimizers/baseminimizer.py", line 498, in _call_minimize
    result = self._minimize(loss=loss, params=params, init=init)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/minimizers/minimizer_minuit.py", line 187, in _minimize
    minimizer = minimizer.migrad(**minimize_options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/iminuit/minuit.py", line 791, in migrad
    fm = migrad(ncall, self._tolerance)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/minimizers/evaluation.py", line 248, in value
    loss_value = self.loss.value(full=self.full)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/loss.py", line 511, in value
    params, checked = self.check_precompile(params=params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/loss.py", line 368, in check_precompile
    self._call_value(
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/z/zextension.py", line 314, in concrete_func
    result = func_to_run(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/loss.py", line 525, in _call_value
    return self._value(
           ^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/loss.py", line 540, in _value
    return self._loss_func(
           ^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/z/zextension.py", line 254, in concrete_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/_loss/binnedloss.py", line 457, in _loss_func
    probs = mod.rel_counts(dat)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/binnedpdf.py", line 1269, in rel_counts
    values = self._call_rel_counts(x, norm)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/z/zextension.py", line 254, in concrete_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/binnedpdf.py", line 1285, in _call_rel_counts
    return self._auto_rel_counts(x, norm=norm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/binnedpdf.py", line 1296, in _auto_rel_counts
    rel_counts = self._rel_counts(x, norm=norm)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/z/zextension.py", line 254, in concrete_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/models/tobinned.py", line 133, in _rel_counts
    values = tf.vectorized_map(integrate_one, limits)[:, 0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/z/zextension.py", line 254, in concrete_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/models/tobinned.py", line 124, in integrate_one
    return pdf.integrate(limits_space, norm=False, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/util/deprecation.py", line 18, in wrapper
    return func(*args, norm=norm, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/z/zextension.py", line 254, in concrete_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/basemodel.py", line 403, in integrate
    integral = self._single_hook_integrate(limits=limits, norm=norm, x=var, options=options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/basemodel.py", line 408, in _single_hook_integrate
    return self._hook_integrate(limits=limits, norm=norm, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/basemodel.py", line 411, in _hook_integrate
    return self._norm_integrate(limits=limits, norm=norm, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/basemodel.py", line 415, in _norm_integrate
    integral = self._limits_integrate(limits=limits, norm=norm, options=options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/basemodel.py", line 424, in _limits_integrate
    integral = self._call_integrate(limits=limits, norm=norm, options=options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/basemodel.py", line 434, in _call_integrate
    return self._integrate(limits, norm, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 3318, in new_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 3262, in new_func
    return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 3295, in new_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/models/truncated.py", line 231, in _integrate
    if limits != self.space:  # we could also do it, but would need to check each limit
       ^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 1159, in __eq__
    return self.equal(other=other, allow_graph=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 1147, in equal
    return equal_space(self, other, allow_graph=allow_graph)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 2540, in equal_space
    return compare_multispace(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 2578, in compare_multispace
    return compare_limits_multispace(space1, space2, comparator=comparator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 2593, in compare_limits_multispace
    compare_limits_coords_dict(space11.get_limits(), space22.get_limits(), comparator=comparator)
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 2619, in compare_limits_coords_dict
    equal.append(compare_limits_dict(limit1_dict, limit2_dict, comparator=comparator))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 2631, in compare_limits_dict
    comparison.append(comparator(limit1, limit2))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 2543, in <lambda>
    comparator=lambda limit1, limit2: limit1.equal(limit2, allow_graph=allow_graph),
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 681, in equal
    return equal_limits(self, other, allow_graph=allow_graph)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/core/space.py", line 821, in equal_limits
    raise IllegalInGraphModeError(msg) from error
zfit.util.exception.IllegalInGraphModeError: Cannot use equality in graph mode, e.g. inside a `tf.function` decorated function. To retrieve a symbolic Tensor, use `.equal(..., allow_graph=True)`
```
## Expected Behaviour
Expected to work as for the unbinned case:

```
import zfit 
import numpy as np

low, high = -5, 10
obs = zfit.Space('obs', low, high)                              # Create the observable space

size_normal = 10_000                                            # Set the size of the normal distribution data
data_normal_np = np.random.normal(size=size_normal, scale=2)    # Generate normal distribution data

data_normal = zfit.Data(data_normal_np, obs=obs)                # Create a zfit Data object with the normal distribution data

mu = zfit.Parameter('mu', 1, -3, 3)                             # Create a parameter for the mean of the first Gaussian
mu2 = zfit.Parameter('mu2', 2, -3, 3)                           # Create a parameter for the mean of the second Gaussian
sigma = zfit.Parameter('sigma', 1, 0.1, 100)                    # Create a parameter for the standard deviation of the first Gaussian
sigma2 = zfit.Parameter('sigma2', 3, 0.1, 100)                  # Create a parameter for the standard deviation of the second Gaussian

gauss = zfit.pdf.Gauss(obs=obs, mu=mu, sigma=sigma)             # Create the first Gaussian PDF
gauss2 = zfit.pdf.Gauss(obs=obs, mu=mu2, sigma=sigma2)          # Create the second Gaussian PDF

pdf = zfit.pdf.SumPDF([gauss, gauss2], [0.5]).to_truncated(
                      limits=[[-5, -3], [3, 10]])               # Create the sum PDF with the two Gaussians

sample = gauss.sample(n=1000)                                   # Generate a sample from the first Gaussian PDF

nll = zfit.loss.UnbinnedNLL(pdf, data_normal)                   # Create the binned negative log-likelihood loss function
minimizer = zfit.minimize.Minuit()                              # Create a Minuit minimizer
result = minimizer.minimize(nll)                                # Minimize the negative log-likelihood function
```

## Context (Environment)

- zfit version: 0.22.0
- Python version: 3.11.8
- Are you using conda, pipenv, etc? : using a `venv` virtual environment
- Operating System: Ubuntu 20.04.6 LTS (Focal Fossa)
- Tensorflow version: 2.16.2

Also tested on:

- zfit version: 0.20.2
- Python version: 3.11.6
- Are you using conda, pipenv, etc? : pipenv
- Operating System: macOs Sonoma 14.2.1 (Intel)
- Tensorflow version: 2.16.1

**Comment by ikrommyd** [comment]
Looks like this line:
```
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/models/truncated.py", line 231, in _integrate
    if limits != self.space:  # we could also do it, but would need to check each limit
```
is causing problems in graph mode if I'm not mistaken. If you disable jit compilation by setting `ZFIT_DO_JIT=0` as an environment variable, it works fine for me.

**Comment by fchinu** [comment]
Dear @ikrommyd, thank you very much for your response. I was able to get the script running by setting the `ZFIT_DO_JIT` environment variable to 0, as you suggested.
However, I've noticed a significant increase in runtime. The script for doing binned fits I sent you now takes 27.6 seconds to execute. For comparison, an unbinned fit previously took 7.34 seconds, but with `ZFIT_DO_JIT=0`, it has increased to 23.22 seconds.
Is there any potential workaround to optimize performance without JIT, or would you recommend adjusting any other settings to improve the fit times?

**Comment by ikrommyd** [comment]
Oh yeah, it shall get fixed. I just offered a temporary workaround that is expected to be slower.

**Comment by ikrommyd** [comment]
@jonas-eschle
I added some breakpoints in `/zfit/core/basemodel.py` and unbinned fits, `limits` is eager
```
(zfit_dev) ➜  zfit git:(develop) ✗ python examples/simple_fit.py
/Users/iason/work/zfit_dev/zfit/zfit/__init__.py:60: UserWarning: TensorFlow warnings are by default suppressed by zfit. In order to show them, set the environment variable ZFIT_DISABLE_TF_WARNINGS=0. In order to suppress the TensorFlow warnings AND this warning, set ZFIT_DISABLE_TF_WARNINGS=1.
  warnings.warn(
> /Users/iason/work/zfit_dev/zfit/zfit/core/basemodel.py(413)_hook_integrate()
-> return self._norm_integrate(limits=limits, norm=norm, options=options)
(Pdb) limits
<zfit Space obs=('x',), axes=(0,), limits=(array([[-2.]]), array([[3.]])), binned=False>
```
In binned fits however, `limits` is lazy,
```
(zfit_dev) ➜  zfit git:(develop) ✗ python examples/simple_fit_binned.py
/Users/iason/work/zfit_dev/zfit/zfit/__init__.py:60: UserWarning: TensorFlow warnings are by default suppressed by zfit. In order to show them, set the environment variable ZFIT_DISABLE_TF_WARNINGS=0. In order to suppress the TensorFlow warnings AND this warning, set ZFIT_DISABLE_TF_WARNINGS=1.
  warnings.warn(
> /Users/iason/work/zfit_dev/zfit/zfit/core/basemodel.py(409)_single_hook_integrate()
-> return self._hook_integrate(limits=limits, norm=norm, options=options)
(Pdb) limits
<zfit Space obs=('x',), axes=(0,), limits=(<tf.Tensor 'loop_body/GatherV2_3:0' shape=(1, 1) dtype=float64>, <tf.Tensor 'loop_body/GatherV2_4:0' shape=(1, 1) dtype=float64>), binned=False>
```
which means that this
```
  File "/home/fchinu/.virtualenv/ml311/lib/python3.11/site-packages/zfit/models/truncated.py", line 231, in _integrate
    if limits != self.space:  # we could also do it, but would need to check each limit
```
will not work. Is this behavior as intended?

**Comment by ikrommyd** [comment]
So, the transformations under:
https://github.com/zfit/zfit/blob/5a41862f2a0c2948e692621ae807737b9dbb40ad/zfit/models/tobinned.py#L103-L118
are what's causing the limits to be lazy. Basically `znp` at that point will spit back lazy tensors.
If you set a breakpoint within the function and do `znp.array([1,2,3])` you will get back a lazy tensor.

**Comment by ikrommyd** [comment]
@jonas-eschle This is a stupid patch for instance that solves these reproducers. Of course not what we want but I think my comments above describe the problem. I don't know the optimal solution though.
```diff
diff --git a/zfit/models/tobinned.py b/zfit/models/tobinned.py
index 0865a0687..450b559ea 100644
--- a/zfit/models/tobinned.py
+++ b/zfit/models/tobinned.py
@@ -104,33 +104,34 @@ class BinnedFromUnbinnedPDF(BaseBinnedFunctorPDF):
     def _rel_counts(self, x, norm):
         del x  # not used, we just return the full histogram
         pdf = self.pdfs[0]
-        edges = [znp.array(edge) for edge in self.axes.edges]
-        edges_flat = [znp.reshape(edge, [-1]) for edge in edges]
+        import numpy as np
+        edges = [np.array(edge) for edge in self.axes.edges]
+        edges_flat = [np.reshape(edge, [-1]) for edge in edges]
         lowers = [edge[:-1] for edge in edges_flat]
         uppers = [edge[1:] for edge in edges_flat]
-        lowers_meshed = znp.meshgrid(*lowers, indexing="ij")
-        uppers_meshed = znp.meshgrid(*uppers, indexing="ij")
+        lowers_meshed = np.meshgrid(*lowers, indexing="ij")
+        uppers_meshed = np.meshgrid(*uppers, indexing="ij")
         shape = tf.shape(lowers_meshed[0])
-        lowers_meshed_flat = [znp.reshape(lower_mesh, [-1]) for lower_mesh in lowers_meshed]
-        uppers_meshed_flat = [znp.reshape(upper_mesh, [-1]) for upper_mesh in uppers_meshed]
-        lower_flat = znp.stack(lowers_meshed_flat, axis=-1)
-        upper_flat = znp.stack(uppers_meshed_flat, axis=-1)
+        lowers_meshed_flat = [np.reshape(lower_mesh, [-1]) for lower_mesh in lowers_meshed]
+        uppers_meshed_flat = [np.reshape(upper_mesh, [-1]) for upper_mesh in uppers_meshed]
+        lower_flat = np.stack(lowers_meshed_flat, axis=-1)
+        upper_flat = np.stack(uppers_meshed_flat, axis=-1)
         options = {"type": "bins"}

         @z.function
         def integrate_one(limits):
-            low, up = tf.unstack(limits)
+            low, up = limits
             limits_space = zfit.Space(obs=self.obs, limits=[low, up])
             return pdf.integrate(limits_space, norm=False, options=options)

-        limits = znp.stack([lower_flat, upper_flat], axis=1)
+        limits = np.stack([lower_flat, upper_flat], axis=1)
         from zfit import run

         try:
             if run.get_graph_mode() is False:
                 msg = "Just stearing the eager execution"
                 raise MapNotVectorized(msg)
-            values = tf.vectorized_map(integrate_one, limits)[:, 0]
+            values = znp.asarray(tuple(map(integrate_one, limits)))
         except (ValueError, MapNotVectorized):
             values = znp.asarray(tuple(map(integrate_one, limits)))
         values = znp.reshape(values, shape)
```

**Comment by fchinu** [comment]
Dear @jonas-eschle, @ikrommyd,
Thank you both for your efforts and for working on the issue. With your latest suggestion, the fit is now functioning correctly. The time performance did not change much with respect to the suggestion of disabling JIT compilation, as disabling graph mode results in a 3-4x increase in runtime for unbinned fits, and the binned fit remains 3-4x slower than the unbinned fits with graph mode enabled, but I see you are working on this. 
Looking forward to your fix!

**Comment by jonas-eschle** [comment]
Long silence, I've been on this since a while, but let me get an update here!

@fchinu you could put only the binned fit under the part
```
with zfit.run.set_graph_mode(False):
   # binned fits here
```
This will at least not slow down the rest.

@ikrommyd 

> Even if we treat the limits eagerly with `numpy` though, they will be converted to lazy in
> 
> https://github.com/zfit/zfit/blob/5a41862f2a0c2948e692621ae807737b9dbb40ad/zfit/models/tobinned.py#L133
> 
> 
> within the `vectorized_map` function.

Yes, exactly, the "problem" with the vectorized map is that it _needs_, by design, to run in "graph mode": it first needs to trace thing "symbolically" before it can "stitch them together" and run as a single operation.


## The problem

I've changed the "equal" in the space to something that makes more sense and doesn't fail. Fine.
But this means that the vectorize now fails with an uncatchable error, 

```
PartialTensorShape: Incompatible shapes during merge: [35,1] vs. [1,1]
	 [[{{node loop_body/Where/pfor/TensorArrayV2Stack/TensorListStack}}]] [Op:__inference__call_value_2471]
```

that does not make sense at all, at least not to me, at least not so far.
Replacing `vectorized_map` with `map_fn` (that is a `tf.while_loop` internally, effectively), it works. It's possible, in principle, that there is different behavior in the vectorized vs map (dynamic things, say broadcasting, maybe doesn't work in the vectorized case).
I have no idea at this point what ever has shape 35. Changing the binning or the limits changes the second or the first number (35 is the first, 1 from [1, 1] the second). It's really puzzling, especially as it works in eager mode or also jitted with the `map_fn`

A fallback to use `map_fn` could be provided, but in principle, this should already happen automatically in the `vectorized_map`. And not ideal if this has to be switched on the user side...

But alas, still looking into this, it's just quite technical seemingly.

@ikrommyd changing the limits to numpy arrays... could probably work too. I guess there is nothing, in principle, that stops us from doing that, as we anyway recompile the method for new PDFs (the self is a python objects, which will trigger recompilation anyways)

**Comment by jonas-eschle** [comment]
@fchinu this should also be resolved now in the git version, please feel free to close if it works

**Comment by fchinu** [comment]
Hi @jonas-eschle, @ikrommyd, thanks for solving the issue, now everything is working!
